### ISSUE TITLE
Processesworker Dim | Missing default values and installations instructions

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal#220]
The processesworker is missing dim related default values (which causes the administration service not starting up) and installations instructions:

```
processesworker:
...
    dim:
      # -- Provide dim client-id from CX IAM centralidp.
      clientId: ""
      # -- Client-secret for dim client-id. Secret-key 'dim-client-secret'.
      baseAddress: ""
      universalResolverAddress: ""
      didDocumentBaseLocation: ""
```
