### ISSUE TITLE
[Portal - BDRS IF] Transition from API Key to Technical User Authentication for BDRS Integration

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal#456]
### Description

We need to update the authentication mechanism for our portal's integration with the BDRS. The current implementation uses an API Key, but it is needed to switch to a new authentication method using a technical user with client ID and secret. 

### Acceptance Criteria

- [x] Replace the API Key authentication with the technical user credentials (client ID and secret etc.).
- [ ] Add following keys to `charts/templates/cronjob-backend-processes.yaml` for `BDRS`
```
            - name: "BPNDIDRESOLVER__USERNAME"
              value: "{{ .Values.backend.placeholder }}"
            - name: "BPNDIDRESOLVER__PASSWORD"
              value: "{{ .Values.backend.placeholder }}"
            - name: "BPNDIDRESOLVER__GRANTTYPE"
              value: "{{ .Values.backend.processesworker.bpnDidResolver.grantType }}"
            - name: "BPNDIDRESOLVER__CLIENTID"
              value: "{{ .Values.backend.processesworker.bpnDidResolver.clientId }}"
            - name: "BPNDIDRESOLVER__CLIENTSECRET"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.backend.interfaces.secret }}"
                  key: "bpndidresolver-client-secret"
            - name: "BPNDIDRESOLVER__SCOPE"
              value: "{{ .Values.backend.processesworker.bpnDidResolver.scope }}"
            - name: "BPNDIDRESOLVER__TOKENADDRESS"
              value: "{{ .Values.centralidp.address }}{{ .Values.backend.keycloak.central.tokenPath }}"
```
